const words = {
    'all' : 'All',
    'all_sche' : 'All Scheduled',
    'run_report': 'Run Report',
    'schedule': 'Schedule',
    'back': 'Back',
    'search': 'Search',
    'view_archived': 'View Archived Report Bookmarks',
    'select': 'Select',
    'today': 'Today',
    'total': 'Total',
    'first': 'First',
    'second': 'Second',
    'table': 'Table',
    'sorted_by': 'Sorted By',
    'send_email': 'Send',
    'select_type': 'Select Type',
    'select_re_type': 'Select Report Type',
    'enter_email_to_send': 'Enter Email Addresses to send this Report',
    'report_delivery': 'Report Delivery',
    'no_data_found': 'No Data Found',
    'created_on': 'Created on',
    'by': 'by',
    'at': 'at',
    'yes': 'Yes',
    'no': 'No',
    'send_report': 'Send report',
    'all_guests': 'All Guests',
    'by_email': 'by email',
    'reset': 'Reset',
    'export_to': 'Export to',
    'tot_amount': 'Total Amount',
    'total_unreturned_key': 'Total Unreturned Keys',
    'no_data_for_selection': 'No report data for this selection',
    'waiting_text': "Please wait, we're loading your report",
    'summary': "Summary",
    'detail': "Detail",
    'rep_sche_name': 'Scheduled Report Name',
    'rep_name': 'Report Name',
    'frequency': 'Frequency',
    'frequency_desc': 'Select how often you would like to send this report via e-mail.',
    'every': 'Every',
    'day': 'Day',
    'days': 'Days',
    'week': 'Week',
    'weeks': 'Weeks',
    'month': 'Month',
    'months': 'Months',
    'year': 'Year',
    'years': 'Years',
    'month_desc': 'Will send the report on the 31st, or the last of the month',
    'on_the': 'On the',
    'of_the_month': 'of the month',
    'year_desc': 'Select one or months to receive this report.',
    'Su': 'Su',
    'Mo': 'Mo',
    'Tu': 'Tu',
    'We': 'We',
    'Th': 'Th',
    'Fr': 'Fr',
    'Sa': 'Sa',
    'Jan': 'Jan',
    'Feb': 'Feb',
    'Mar': 'Mar',
    'Apr': 'Apr',
    'May': 'May',
    'Jun': 'Jun',
    'Jul': 'Jul',
    'Aug': 'Aug',
    'Sep': 'Sep',
    'Oct': 'Oct',
    'Nov': 'Nov',
    'Dec': 'Dec',
    'date_range': 'Date range',
    'date_range_desc': 'Select the time frame you would want to include the report.',
    'yesterday': 'Yesterday',
    'last_week': 'Last Week',
    'last_month': 'Last Month',
    'custom': 'Custom',
    'week_starting_on': 'Last week starting on',
    'sat': 'Saturday',
    'sun': 'Sunday',
    'mon': 'Monday',
    'tue': 'Tuesday',
    'wed': 'Wednesday',
    'thu': 'Thursday',
    'fri': 'Friday',
    'the_last': 'The Last',
    'day_report': 'Include day report is sent.',
    'no_date_specific_content': "This report doesn't include date-specific content. All available data will be printed.",
    'rep_sche_time': 'Report Schedule Time',
    'rep_sche_time_desc': 'Select a time you want the report to be delivered. Delivery times are relative to the property.',
    'rep_first_delivery': 'Report will first be delivered on',
    'rep_sche_on': 'Report will first be scheduled on',
    'rep_sche_at': 'Report will first be scheduled at or after',
    'at_or_after': 'at or after',
    'audience': 'Recipients',
    'cancel': 'Cancel',
    'review': 'Review',
    'required_field': 'this field is required',
    'required_email': 'this should be an email',
    'sche_name_req': 'Schedule name is required',
    'week_req': 'Week day is required',
    'date_req': 'Date is required',
    'month_req': 'Month is required',
    'end_time_req': 'End time of schedule is required',
    'delivery_time_req': 'Delivery Time is required',
    'audience_req': 'Audience is required',
    'rep_bookmark_name': 'Report Bookmark Name',
    'day_to_deliver': 'Day(s) to Deliver',
    'rep_start_time': 'Report Start Time',
    'go_back': 'Go Back',
    'schedule_bookmark': 'Schedule and Bookmark',
    'finalize_bookmark': 'Finalize and Bookmark',
    'sche_cancel_alert': 'Are you sure you want to cancel Scheduling this report?',
    'action': 'Action',
    'edit': 'Edit',
    'archive': 'Archive',
    'delete': 'Delete',
    'ok':'OK',
    'archive_del_alert': 'Are you sure you want to delete this scheduled report permanently?',
    'archive_mgs': "Archiving a Report Bookmark will make it inactive. The system removes any planned schedules on this report bookmark. The report bookmark will be available for later reference. It won't delete it",
    'rep_bookmark_status': 'Report Bookmark Status',
    'archive_inactive': 'Inactive (Archived)',
    'inactive': 'Inactive',
    'active': 'Active',
    'day_date_month': 'Day/Date/Month (if applicable)',
    'bookmarked_date': 'Bookmarked Date',
    'date_archived': 'Date Archived',
    'view_audience': 'View Audience (email)',
    'num_of_props': 'Number of Properties',
    'prop_access_mgs_one': 'One or more properties in this report bookmark is no longer available for your access. The report bookmark will be modified to use ONLY the properties that you have accessed to within the chosen ones.',
    'prop_access_mgs_two': 'None of the properties that are chosen in this report bookmark is accessible to you. With that, this report bookmark will be archived automatically. If needed, you can create new report bookmarks at any time.',
    'view_props': 'View Properties',
    'audience_email': 'Audience (e-mails)',
    'prop_incl_bookmark': 'Properties included in this Report Bookmark',
    'access_status': 'Access Status',
    'enter_audience_email': 'Enter email addresses for the audience you would like to send this report to',
    'enter_schedule_name': 'Enter Schedule Name',
    'view': 'View',
    'type_to_search':'Type to search',
    'enter_or_select_author_replace': "Enter or select author to replace",
    'enter_or_select_replace': "Enter or select author to replace with",
    'admin_panel':'Admin Panel',
    'Report has been scheduled': 'Report has been scheduled!',
    'Report has been updated': 'Report has been updated',
    'Your message has been sent!': 'Your message has been sent!',
    'This report bookmark has been successfully archived!!':'This report bookmark has been successfully archived!!',
    'This report bookmark has been successfully deleted!!':'This scheduled report has been successfully deleted!!',
    'starting_date_warning': "Starting date can't be after end date.",
    'report_library': 'Report Library',
    'favorite': 'Save as a favorite report.',
    'save': 'Save',
    'expand': 'Expand',
    'collapse': 'Collapse',
    'week_desc': 'Send the report every',
    'select_frequency': 'Select Frequency',
    'am': 'AM',
    'pm': 'PM',
    'to': 'To',
    'favourites_added_success': "Added to favorites! ",
    'view_favourites': "View Favorites",
    'favourites_removed_success': "Removed from favorites!",
    'library' : "Library",
    'favourites': "Favorites",
    'scheduled': "Scheduled",
    'all_reports': "All Reports",
    'change_filters': "Change Filters",
    'scheduled_reports': "Scheduled Reports",
    'archived_reports': "Archived Reports",
    'view_archived_reports': "View Archived Reports",
    'view_scheduled_reports': "View Scheduled Reports",
    'email_address': "Email Address",
    'file_type': "File Type",
    'your_email': "Your email",
    'subject': "Subject",
    'asc': "Ascending",
    'desc': "Descending",
    'most_recent': "Most Recent",
    'building_your_report': "Building your report",
    'fetching_your_scheduled_report': "Fetching your scheduled report",
    'after': "after",
    'invalid_email_address': "Invalid Email Address",
    'No_matching_search_results': "Sorry, no results found.",
    'Press_enter_to_add': "Press enter to add",
    'enter_subject': "Enter Subject",
    'generated': "Generated",
    'edit_recipient': "Edit Recipients",
    'author': "Author",
    'company': "Company",
    'has': "has",
    'active_sche_reports': "active scheduled reports",
    'edit_author': "Edit Author",
    'replace_author': "Replace Author",
    'author_to_replace': "Author to Replace",
    'has_replaced_with': "has been replaced with",
    'email_replaced_successfully': "Email has been replaced successfully.",
    'replace_with': "Replace with",
    'enter_or_select_email': "Enter or select email addresses to edit",
    'enter_or_select_author': "Select author to replace",
    'select_user_to_replace_with': "Select user to replace with",
    'complete': "Complete",
    'reports': "Reports",
    'report': "Report",
    'select_which_reports': "Select which Reports action applies to",
    'recipient': "Recipient",
    'recipients': "Recipients",
    'add_recipient': "Add Recipient",
    'remove_recipient': "Remove Recipient",
    'replace_recipient': "Replace Recipient",
    'choose_action': "Choose action type",
    'select_email_to_remove': "Select email addresses to edit",
    'select_email_to_replace': "Select email addresses to replace",
    'Email(s) have been removed successfully!': "Email(s) have been removed successfully!",
    'Email(s) have been added successfully!': "Email(s) have been added successfully!",
    'no_result_found': "No results found.",
    'no_result_found_reason': "We couldn’t find what you were looking for. Check your filters and try again.",
    'report_would_include': "Report would include",
    'if_sent_today': "if the report was sent today.",
    'default': "Default",
    'list_is_empty': "List is empty",
    'confirm_data_load': "The number of records exceeds the maximum allowable limit",
    'proceed_anyway': "Proceed Anyway",
    'no_author_found': "No Author Found",
    'and': "and",
    'more': "more",
    "January": "January",
    "February": "February",
    "March": "March",
    "April": "April",
    "June": "June",
    "July": "July",
    "August": "August",
    "September": "September",
    "October": "October",
    "November": "November",
    "December": "December",
    "report_cannot_be_run_message": "This report cannot be run because there is no data."
}

export default words